# Example configuration for clone frequency tracking
# This demonstrates how to enable and use the clone frequency tracking feature

# Patient and analysis identification
patient_id: "CRUK0044"
analysis_mode: "fixed"  # Can be "dynamic" or "fixed"

# Input file paths
input_files:
  aggregation_dir: "/path/to/aggregation_results"
  ssm_file: "/path/to/ssm.txt"
  longitudinal_data: "/path/to/longitudinal_data.csv"
  code_dir: "/path/to/tracerx-mp"

# Output configuration
output:
  base_dir: "/path/to/output"
  create_subdirs: true

# Analysis parameters
parameters:
  n_markers: 2
  read_depth: 90000
  method: "phylowgs"
  lambda1: 0.0  # Weight for fraction-based objective
  lambda2: 1.0  # Weight for structure-based objective
  focus_sample: 0
  track_clone_freq: true  # ENABLE CLONE FREQUENCY TRACKING

# Fixed marker specification (required for fixed mode)
fixed_markers:
  - "DLG2_11_83544685_T>A"
  - "GPR65_14_88477948_G>T"
  - "C12orf74_12_93100715_G>T"
  - "CSMD1_8_2975974_G>T"
  - "OR51D1_11_4661941_G>T"

# Optional filtering
filtering:
  timepoints: []  # Empty = all timepoints

# Visualization options
visualization:
  generate_plots: true  # Enable all plots including clone frequency plots
  plot_format: "png"
  save_intermediate: false

# Validation and debugging
validation:
  validate_inputs: true
  debug_mode: false